package org.uob.a2.parser;

import java.util.ArrayList;
import java.util.List;

/**
 * The {@code Tokeniser} class is responsible for converting a string input into a list of tokens
 * that can be parsed into commands by the game.
 * 
 * <p>
 * The tokeniser identifies keywords, variables, and special symbols, assigning each a {@code TokenType}.
 * </p>
 */
public class Tokeniser {

    private ArrayList<Token> tokens; // List of tokens generated by the tokeniser

    // Public constructor
    public Tokeniser() {
        tokens = new ArrayList<>(); // Initialize the list of tokens
    }

    // Method to retrieve the list of tokens generated by the tokeniser
    public ArrayList<Token> getTokens() {
        return tokens;
    }

    // Method to sanitize the input string by converting it to lowercase and trimming whitespace
    public String sanitize(String s) {
        return s.trim().replaceAll("\\s+", " ").toLowerCase();
    }

    // Method to sanitise (with "s") the input string for compatibility with tests
    public String sanitise(String s) {
        return sanitize(s);
    }

    // Method to tokenize the input string into a list of Token objects based on keywords and patterns
    public void tokenize(String s) {
        tokens.clear(); // Clear previous tokens
        String sanitizedInput = sanitize(s);

        // split using space
        String[] parts = sanitizedInput.split(" ");

        for (String tokenValue : parts) {
            switch (tokenValue) {
                case "move":
                    tokens.add(new Token(TokenType.MOVE, tokenValue));
                    break;
                case "get":
                    tokens.add(new Token(TokenType.GET, tokenValue));
                    break;
                case "drop":
                    tokens.add(new Token(TokenType.DROP, tokenValue));
                    break;
                case "use":
                    tokens.add(new Token(TokenType.USE, tokenValue));
                    break;
                case "on":
                    tokens.add(new Token(TokenType.PREPOSITION, tokenValue));
                    break;
                case "look":
                    tokens.add(new Token(TokenType.LOOK, tokenValue));
                    break;
                case "status":
                    tokens.add(new Token(TokenType.STATUS, tokenValue));
                    break;
                case "help":
                    tokens.add(new Token(TokenType.HELP, tokenValue));
                    break;
                case "quit":
                    tokens.add(new Token(TokenType.QUIT, tokenValue));
                    break;
                case "combine":
                    tokens.add(new Token(TokenType.COMBINE, tokenValue)); 
                    break;
                default:
                    tokens.add(new Token(TokenType.VAR, tokenValue));
                    break;
            }
        }

        tokens.add(new Token(TokenType.EOL, ""));
    }

    // Adding tokenise method to convert string input into list of tokens
    public List<Token> tokenise(String input) {
        tokenize(input);
        return tokens;
    }
}
